version: '3'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - data:/var/lib/mysql

volumes:
  data: